const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.GM_SDK,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Text.Exps.TagAt,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.anglediff,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Timer.Acts.PauseResumeAllTimers,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{ArmLower: 0},
	{ArmUpper: 0},
	{Head: 0},
	{LegLower: 0},
	{LegUpper: 0},
	{TorsoLower: 0},
	{TorsoUpper: 0},
	{Rope: 0},
	{orientationX: 0},
	{orientationY: 0},
	{minAngle: 0},
	{maxAngle: 0},
	{playerJoint: 0},
	{cpuOrder: 0},
	{jointName: 0},
	{Tween: 0},
	{Joint: 0},
	{Sine: 0},
	{Head2: 0},
	{Background: 0},
	{Mouse: 0},
	{Timer: 0},
	{GameTimer: 0},
	{MarkObjective: 0},
	{MarkYou: 0},
	{NextButton: 0},
	{visiblePosition: 0},
	{invisiblePosition: 0},
	{NiceJob: 0},
	{ObjectiveBar: 0},
	{ObjectiveBarBG: 0},
	{ObjectiveBarMask: 0},
	{TextTimeSeconds: 0},
	{ObjectiveBarShadow: 0},
	{Fader: 0},
	{TextTimeColon: 0},
	{TextTimeMinutes: 0},
	{TextFinalScore: 0},
	{TextTimeSeconds2: 0},
	{TextTimeSeconds3: 0},
	{TextTimeSeconds4: 0},
	{TextTimeSeconds5: 0},
	{TutorialIcons: 0},
	{TutorialBG: 0},
	{enabled: 0},
	{TutorialButton: 0},
	{hiddenPosition: 0},
	{TutorialText: 0},
	{Start: 0},
	{Touch: 0},
	{ScoreText: 0},
	{LocalStorage: 0},
	{Home: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{eksplozija: 0},
	{Sprite4: 0},
	{Home2: 0},
	{BSound: 0},
	{BSound2: 0},
	{Audio: 0},
	{efekt: 0},
	{Restart: 0},
	{Sine2: 0},
	{Sprite6: 0},
	{eksplozija2: 0},
	{stoptime: 0},
	{adscore: 0},
	{unazad: 0},
	{moregamess: 0},
	{Browser: 0},
	{y8: 0},
	{playerName: 0},
	{Loginy8moja: 0},
	{Anchor: 0},
	{StarsFont: 0},
	{StarsFont1: 0},
	{StarsFont2: 0},
	{StarsFont3: 0},
	{leaderboard: 0},
	{lagged: 0},
	{GameMonetizeSDK: 0},
	{BodyParts: 0},
	{BodyPartsCPU: 0},
	{sound: 0},
	{SoundEf: 0},
	{tutorialState: 0},
	{prevX: 0},
	{prevY: 0},
	{selectedJointUID: 0},
	{selectAngle: 0},
	{moveDirection: 0},
	{moveOrientation: 0},
	{gameOver: 0},
	{Highscore: 0},
	{Score: 0},
	{roundTime: 0},
	{maxErrorValue: 0},
	{cpuMoving: 0},
	{MOVE_SENSITIVITY: 0},
	{x: 0},
	{a1: 0},
	{a2: 0},
	{b1: 0},
	{b2: 0},
	{timeString: 0},
	{OB_MIN_SIZE: 0},
	{OB_MAX_SIZE: 0},
	{MIN_ERROR: 0},
	{MAX_ERROR: 0},
	{maxError: 0},
	{playerAngle: 0},
	{sumOfDiffs: 0},
	{nearbyJointDetected: 0}
];

self.InstanceType = {
	ArmLower: class extends self.ISpriteInstance {},
	ArmUpper: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	LegLower: class extends self.ISpriteInstance {},
	LegUpper: class extends self.ISpriteInstance {},
	TorsoLower: class extends self.ISpriteInstance {},
	TorsoUpper: class extends self.ISpriteInstance {},
	Rope: class extends self.ITiledBackgroundInstance {},
	Joint: class extends self.ISpriteInstance {},
	Head2: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	GameTimer: class extends self.ISpriteInstance {},
	MarkObjective: class extends self.ISpriteInstance {},
	MarkYou: class extends self.ISpriteInstance {},
	NextButton: class extends self.ISpriteInstance {},
	NiceJob: class extends self.ISpriteInstance {},
	ObjectiveBar: class extends self.ITiledBackgroundInstance {},
	ObjectiveBarBG: class extends self.ISpriteInstance {},
	ObjectiveBarMask: class extends self.ISpriteInstance {},
	TextTimeSeconds: class extends self.ITextInstance {},
	ObjectiveBarShadow: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTimeColon: class extends self.ITextInstance {},
	TextTimeMinutes: class extends self.ITextInstance {},
	TextFinalScore: class extends self.ITextInstance {},
	TextTimeSeconds2: class extends self.ITextInstance {},
	TextTimeSeconds3: class extends self.ITextInstance {},
	TextTimeSeconds4: class extends self.ITextInstance {},
	TextTimeSeconds5: class extends self.ITextInstance {},
	TutorialIcons: class extends self.ISpriteInstance {},
	TutorialBG: class extends self.ITiledBackgroundInstance {},
	TutorialButton: class extends self.ISpriteInstance {},
	TutorialText: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Home: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	eksplozija: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Home2: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	BSound2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	efekt: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	eksplozija2: class extends self.ISpriteInstance {},
	stoptime: class extends self.ISpriteInstance {},
	adscore: class extends self.ISpriteInstance {},
	unazad: class extends self.ISpriteInstance {},
	moregamess: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	y8: class extends self.ISpriteInstance {},
	playerName: class extends self.ITextInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	StarsFont: class extends self.ISpriteFontInstance {},
	StarsFont1: class extends self.ITextInstance {},
	StarsFont2: class extends self.ISpriteFontInstance {},
	StarsFont3: class extends self.ISpriteFontInstance {},
	leaderboard: class extends self.ISpriteInstance {},
	lagged: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	BodyParts: class extends self.ISpriteInstance {},
	BodyPartsCPU: class extends self.ISpriteInstance {}
}